version: '3.1'

services:
  db:
   image: mysql
   restart: always
   container_name: database
   ports:
    - 3306:3306
   environment:
     MYSQL_DATABASE: magazin
     MYSQL_ROOT_PASSWORD: root
     MYSQL_USER: test
     MYSQL_PASSWORD: test
   volumes:
    - ./dump:/docker-entrypoint-initdb.d

  
  web:
   build: ./go
   ports:
    - "1337:1337"


  